### ISSUE TITLE
Usage of cached apt catalogs lead to missing packages

### ISSUE THREAD

**Issue by megian** [projectsyn/floodgate#10]
Currently we do cache the apt catalog in the container image docker.io/projectsyn/suc-ubuntu-bionic. Since regular package mirrors do not hold the previous binaries, this might lead to errors.

## Steps to Reproduce the Problem

  1. Use an outdated system
  1. The time gate is not yet fullfilled (so it uses the previous tag)

## Actual Behavior
```
2020-09-17 16:58:40 UTC [info] SUC - Doing package upgrade
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  cloud-init containerd.io open-vm-tools
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 422 kB/22.4 MB of archives.
After this operation, 110 kB disk space will be freed.
Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 cloud-init all 20.2-45-g5f7825e2-0ubuntu1~18.04.1
  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cloud-init/cloud-init_20.2-45-g5f7825e2-0ubuntu1~18.04.1_all.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
2020-09-17 16:58:43 UTC [error] SUC - Package upgrade failed

```

## Expected Behavior
* No update in the case of the maintenance time is not yet reached
* An cache server with old packages is used

**Comment by glrf** [comment]
We decided to solve this by updating packages by default. Closed by https://github.com/projectsyn/system-upgrade-controller-package-upgrade/pull/29
